version: "3.9"

services:
  db:
    image: postgres:15
    container_name: data_pipeline_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: data_pipeline_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
    volumes:
      - ./data:/app/data
    command: ["python", "src/main.py"]

volumes:
  pgdata:
